# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

crossdist <- function(m1) {
    .Call(`_SPDEcensSpatial_crossdist`, m1)
}

saemEsp <- function(y, X, cc, coords, init_phi, init_gamma, lower, upper, lowerp, upperp, M, Maxiter, pc, tol, mats, infMat) {
    .Call(`_SPDEcensSpatial_saemEsp`, y, X, cc, coords, init_phi, init_gamma, lower, upper, lowerp, upperp, M, Maxiter, pc, tol, mats, infMat)
}

prediccion <- function(model, mats, Apred, Xnew, coordnew, cpred) {
    .Call(`_SPDEcensSpatial_prediccion`, model, mats, Apred, Xnew, coordnew, cpred)
}

